- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/common.yml
  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/essentials/server.yml
    - import_tasks: tasks/tools/server.yml
