- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/common.yml
  tasks:
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/essentials.yml
    - import_tasks: tasks/applications/main.yml
    - import_tasks: tasks/tools/main.yml
    - import_tasks: tasks/dotfiles.yml

