
- name: Update apt package cache 
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"

- name: Update Pacman package cache 
  become: true
  pacman:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Archlinux"

