# Install essential packages for Debian-based systems
- name: Install essential packages (Debian-based)
  become: true
  apt:
    name:
      - build-essential
      - i3
      - curl
      - git
      - fontconfig
      - unzip
      - htop
      - python3-apt
      - python3-pip
      - python3-virtualenv
      - zsh
      - tmux
      - ripgrep
      - fzf
      - dmenu
      - stow
      - jq
      - sshfs
    state: present
  when:
    - ansible_facts['os_family'] == "Debian"

# Install essential packages for Arch-based systems
- name: Install essential packages (Arch-based)
  become: true
  pacman:
    name:
      - base-devel
      - i3
      - curl
      - git
      - fontconfig
      - unzip
      - python
      - python-pip
      - zsh
      - tmux
      - ripgrep
      - fzf
      - dmenu
      - stow
      - jq
      - sshfs
    state: present
  when:
    - ansible_facts['os_family'] == "Archlinux"
