- name: Install essential packages (Debian-based)
  become: true
  apt:
    name:
      - build-essential
      - curl
      - git
      - unzip
      - htop
      - zsh
      - fzf
      - stow
      - fail2ban
      - jq
    state: present
  when:
    - ansible_facts['os_family'] == "Debian"
