---

- name: Check if Firefox is installed
  command: which firefox
  register: has_firefox
  ignore_errors: true

- name: Install Firefox if not present
  when: has_firefox.rc != 0
  block:
    - name: Create a directory for APT repository keys
      become: true
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Import the Mozilla APT repository signing key
      become: true
      shell: wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null

    - name: Verify the GPG key fingerprint
      become: true
      shell: >
        gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc |
        awk '/pub/{getline; gsub(/^ +| +$/,""); if($0 == "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3") print "\nThe key fingerprint matches ("$0").\n"; else print "\nVerification failed: the fingerprint ("$0") does not match the expected one.\n"}'
      register: gpg_verification
      changed_when: false
      failed_when: "'Verification failed' in gpg_verification.stdout"

    - name: Add Mozilla APT repository to sources list
      become: true
      lineinfile:
        path: /etc/apt/sources.list.d/mozilla.list
        line: 'deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main'
        create: yes

    - name: Create APT preferences file for Mozilla repository
      become: true
      copy:
        dest: /etc/apt/preferences.d/mozilla
        content: |
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000

    - name: Update package list and install Firefox
      become: true
      apt:
        name: firefox
        update_cache: yes
