# https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_amd64.deb
#
- name: Check if delta is installed
  shell: "which delta"
  register: has_delta
  ignore_errors: true

- name: Install delta via release .deb file
  become: true
  apt:
    deb: "https://github.com/dandavison/delta/releases/download/0.18.2/git-delta_0.18.2_amd64.deb"
  when: ansible_facts['os_family'] == "Debian" and has_delta is failed

