- import_tasks: fonts.yml
- import_tasks: nvim.yml
- import_tasks: zsh.yml
- import_tasks: smug.yml
- import_tasks: delta.yml
- import_tasks: starship.yml
- import_tasks: zoxide.yml
- import_tasks: rofi.yml
- import_tasks: aws-cli.yml
- import_tasks: nvm.yml
