---

- name: Check if zoxide is installed
  shell: "which zoxide"
  register: has_zoxide
  ignore_errors: true

- name: Install zoxide
  when: has_zoxide is failed
  shell:
    cmd: "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh -s -- --bin-dir /usr/local/bin"
