- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: latest

- name: Install oh-my-zsh
  shell:
    cmd: "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Change shell to zsh
  user:
    shell: /bin/zsh
